[[main]]
    identifier = "about"
    name = "About"
    url = "about/"
    weight = 1

[[main]]
    identifier = "blog"
    name = "Blog"
    url = "blog/"
    weight = 2

[[main]]
    identifier = "docs"
    name = "Docs"
    url = "docs/"
    weight = 3